version: '3.8'
services:
  web:
    container_name: apache-bare
    image: httpd:latest
    ports:
    - "8080:80"
    networks:
    - red_caddy
    volumes:
    - ./html:/usr/local/apache2/htdocs/


networks:
  red_caddy:
    external: true
